# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-20 23:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=200)),
                ('destination_account_id', models.IntegerField(blank=True, null=True)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('D', 'Deposit'), ('W', 'Withdrawal'), ('T', 'Transfer'), ('F', 'Bank Fee')], max_length=15)),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='bankapp.Account')),
            ],
            options={
                'ordering': ['-transaction_time'],
            },
        ),
    ]
