# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='destination_account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
