# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_auto_20160306_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('d', 'Deposit'), ('w', 'Withdrawal'), ('t', 'Transfer')], default='d', max_length=15),
            preserve_default=False,
        ),
    ]
